name: >
  Build Apple's Game Porting Toolkit for use with Mythic.
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_gptk:
    name: Build GPTK
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Tap homebrew-apple
        run: brew tap whisky/apple http://github.com/Whisky-App/homebrew-apple
        
      - name: Check cache for compiler
        id: compiler-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/Cellar/game-porting-toolkit-compiler
          key: game-porting-toolkit-compiler-0.1
          
      - name: >
          Install compiler (If it's not already cached)
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        run: brew install whisky/apple/game-porting-toolkit-compiler
        
      - name: Save compiler to cache
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          key: game-porting-toolkit-compiler-0.1
          path: /usr/local/Cellar/game-porting-toolkit-compiler
          
      - name: >
          Relink compiler (If it's cached)
        if: steps.compiler-cache.outputs.cache-hit == 'true'
        run: |
          brew install whisky/apple/game-porting-toolkit-compiler
          ln -s /usr/local/Cellar/game-porting-toolkit-compiler/0.1/ /usr/local/opt/game-porting-toolkit-compiler
          
      - name: Install taps
        run: brew install whisky/apple/game-porting-toolkit winetricks || true
        
      - name: Trim Files
        run: |
          rm -rf $(brew --prefix game-porting-toolkit)/.brew
          rm -rf $(brew --prefix game-porting-toolkit)/include
          rm -rf $(brew --prefix game-porting-toolkit)/INSTALL_RECEIPT.json
          rm -rf $(brew --prefix game-porting-toolkit)/share/man
          find $(brew --prefix game-porting-toolkit)/bin -type f -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          find $(brew --prefix game-porting-toolkit)/bin -type l -delete
          
      - name: Create Libraries folder
        run: mkdir -p Libraries/Wine
        
      - name: Copy taps into Libraries
        run: |
          cp -a $(brew --prefix game-porting-toolkit)/. Libraries/Wine/
          cp -a $(brew --prefix winetricks)/bin/winetricks Libraries/
          
      - name: Copy external dependencies
        run: cp -a libs/. Libraries/Wine/lib/
          
      - name: Copy DXVK into Libraries
        run: cp -a DXVK Libraries/
        
      - name: Copy Version PList
        run: cp -a GPTKVersion.plist Libraries/
        
      - name: Install GPTK
        run: |
          ditto GPTK/redist/lib/ Libraries/Wine/lib/
          ln -s ./external/libd3dshared.dylib Libraries/Wine/lib/libd3dshared.dylib
          ln -s ./external/D3DMetal.framework Libraries/Wine/lib/D3DMetal.framework
          
      - name: Compress Libraries (.tar.xz)
        run: tar -cJf Libraries.txz Libraries
          
      - name: Upload Libraries Archive to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: Libraries.txz
